### ISSUE TITLE
Polish translation for Community Edition 6.1

### ISSUE THREAD

**Issue by tjudycki** [webdetails/pentahoLanguagePacks#131]
Hi!

I need a localised version of Pentaho CE 6.1 and I would like to cooperate. I see that many files are translated already in data/pl folder. My questions:
1. How exactly should I translate? Browse manually through all subdirectories and open each file to check if it's translated?
2. There is a file translations/nl/translation.xls which seems to group all text together. Is it possible to generate such file for any other language, translate it and distribute translated text into proper places?
3. How can I install language pack when it's finished? If I understand well, I need to build id:
ant -DlangCode=pl build-language-pack
and then modify somehow data-integration\system\karaf\system\org\pentaho\pentaho-marketplace-di\6.1.0.1-196\pentaho-marketplace-di-6.1.0.1-196-pentaho-marketplace-config.cfg to install plugin from local resources?

Regards,

Tomasz Judycki

**Comment by carlosrusso** [comment]
Welcome aboard!

1) Go through all the .properties files and check if they are translated. Typically you will find lines with a <TRANSLATE ME> tag

2) The file `translations/nl/translation.xls` results from the individual effort from the maintainer of the dutch language pack. If you would like to use a similar scheme, please contact Cees (lookup the email in data/nl/metadata.json).

3) Upon running `ant -DlangCode=pl build-language-pack`, the `dist` folder will contain a file `languagePack_pl_*.zip`. You can manually install the plugin by simply unzipping that file onto `pentaho-solutions/system`, so that you end up having a `pentaho-solutions/system/languagePack_pl` folder. You'll need to restart the server to be able to use the installer.

**Comment by tjudycki** [comment]
Carlo!

Thanks for your explanation. I'm trying to reach Cees, however his address in nl/metadata.json seems outdated.

Another question: why .js files are not tagged with "TRANSLATE ME"? For example data\pl\system\admin-plugin\resources\nls\pl\messages.js is translated while data\pl\system\pentaho-jpivot-plugin\adhoc\js\ui\messages\nls\pl\message_strings.js is not, but there is no TRANSLATE ME tag.

**Comment by carlosrusso** [comment]
The "TRANSLATE ME" tag was introduced for the convenience of the translators.
When the language packs are "compiled", the "TRANSLATE ME" tags are automatically removed. 

We didn't bother placing the "TRANSLATE ME" tag on those files because there were just a handful of .js files.

**Comment by tjudycki** [comment]
Indeed: there is just 5 .js files. However it's almost 700 lines to translate.

What I managed to do yesterday evening: I wrote a simple Java program to export all text from .js and .properties files into .csv with columns:
- file name
- line number
- property code
- text to be translated
- TRANSLATE ME tag.
Also text is exported into .txt file. What I plan to do: I'll translate .txt file by Google Translator. It works pretty well with that kind of vocabulary. Then I'll paste translation back into .csv, verify quality of translation manually and write next Java procedure to store all texts back into .js and .properties.

In my opinion it's fast and convenient method. Other translators may also use it. What do you think?

**Comment by carlosrusso** [comment]
Sure, why not?

**Comment by carlosrusso** [comment]
This thread is inactive for some time and it is not really an issue. I'm closing it for now.
