### ISSUE TITLE
Can't not open the languagePackInstaller tab

### ISSUE THREAD

**Issue by lanlan1128** [webdetails/pentahoLanguagePacks#142]
HI,this is the screenshoot
![image](https://user-images.githubusercontent.com/13283444/43514316-8740368e-95b2-11e8-907c-b3fd18a6ded2.png)

and the log is
![image](https://user-images.githubusercontent.com/13283444/43514359-a3f50b7e-95b2-11e8-9a90-cf80aa09ec16.png)

Can you give me some solution?

**Comment by pamval** [comment]
Not sure what you're trying to do. If you're trying to install the available language packs on a 8.1 server, the solution is simple - it won't work and that's why they are not available for 8.1 on the marketplace.

If you're trying to build a new version of a language pack, you can set the dependencies for cpf and cpk to use the 9.0.0.0-SNAPSHOT version (you can edit the build.properties file and there'll be a dependency.pentaho-cpk-plugin.revisionand dependency.pentaho-cpf-plugin.revision). That'll make the language pack run in 8.1
